### ISSUE TITLE
idea插件安装不上

### ISSUE THREAD

**Issue by tmjGitAccount** [momosecurity/momo-code-sec-inspector-java#1]
idea版本2020.2
安装后无反应，刷新后又显示未安装

**Comment by retanoj** [comment]
测试如下版本安装正常
IntelliJ IDEA 2020.2.3 (Community Edition)
Build #IC-202.7660.26, built on October 6, 2020
Runtime version: 11.0.8+10-b944.34 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: ide.intellij.laf.enable.animation=true, ide.balloon.shadow.size=0, ide.images.show.chessboard=true
Non-Bundled Plugins: com.intellij.ideolog, Lombook Plugin, Momo Code Sec Inspector (Java)


能否点击菜单栏 Intellij IDEA  -> About Intellij IDEA -> 复制按钮，将内容贴过来？

**Comment by tmjGitAccount** [comment]
> 测试如下版本安装正常
> IntelliJ IDEA 2020.2.3 (Community Edition)
> Build #IC-202.7660.26, built on October 6, 2020
> Runtime version: 11.0.8+10-b944.34 x86_64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> macOS 10.15.7
> GC: ParNew, ConcurrentMarkSweep
> Memory: 2014M
> Cores: 4
> Registry: ide.intellij.laf.enable.animation=true, ide.balloon.shadow.size=0, ide.images.show.chessboard=true
> Non-Bundled Plugins: com.intellij.ideolog, Lombook Plugin, Momo Code Sec Inspector (Java)
> 
> 能否点击菜单栏 Intellij IDEA -> About Intellij IDEA -> 复制按钮，将内容贴过来？


IntelliJ IDEA 2020.2.2 (Ultimate Edition)
Build #IU-202.7319.50, built on September 15, 2020
Licensed to https://zhile.io
You have a perpetual fallback license for this version
Subscription is active until July 8, 2089
Runtime version: 11.0.8+10-b944.31 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: Batch Scripts Support, CMD Support, GrepConsole, Lombook Plugin, org.avaje.ebean11.enhancer, org.sonarlint.idea, MavenRunHelper, org.jetbrains.kotlin, com.ccnode.codegenerator.MyBatisCodeHelperPro

**Comment by retanoj** [comment]
IntelliJ IDEA 2020.2.2 (Ultimate Edition)
Build #IU-202.7319.50, built on September 15, 2020
Licensed to Intellij IDEA Evaluator

Runtime version: 11.0.8+10-b944.31 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Window  10

依次安装插件：
- Batch Scripts Support
- CMD Support
- Grep Console
- Lombok Plugin
- Ebean  enhancer
- SonarLint
- Maven Helper
- Kotlin
- MyBatisCodeHelperPro

最后安装本插件，未发现问题，未能复现问题。

请再次尝试安装，如安装失败，可以查看日志以获取有用信息。
查看日志方法
1）打开项目的情况下，Help -> Show Log in Explorer
2)  未打开项目的情况下，Configure -> Compress Logs and show in  File Manager

**Comment by retanoj** [comment]
抱歉，多次尝试，问题无法复现。
先关闭该issue，如有问题欢迎继续沟通。
