### ISSUE TITLE
fastjson策略中，源码存在错误

### ISSUE THREAD

**Issue by k4n5ha0** [momosecurity/momo-code-sec-inspector-java#11]
https://github.com/momosecurity/momo-code-sec-inspector-java/blob/2018.3/src/main/java/com/immomo/momosec/lang/java/rule/momosecurity/FastjsonAutoType.java

描写的是fastjson漏洞，但是第三十行写的是jackson的漏洞描述如下：
* com.fasterxml.jackson.core:jackson-databind 在开启DefaultTyping时，存在反序列化风险

**Comment by retanoj** [comment]
感谢。。。
