### ISSUE TITLE
硬编码凭证熵与阈值判断有问题

### ISSUE THREAD

**Issue by ZyjacyaD** [momosecurity/momo-code-sec-inspector-java#12]
src\main\java\com\immomo\momosec\lang\java\rule\momosecurity\HardcodedCredentials.java
136行，此处计算字符串熵的判断应该为小于才比较贴合实际吧，不然连测试例子中的admin_passwd都检测不出来，作用不大。反而那些又臭又长的一般就认为加密过或者不是密码。

**Comment by retanoj** [comment]
对于阈值大小的疑问是个好疑问，我说下当时设定这个时候的考量吧。
HardcodedCredentials 这个规则最初希望检查出硬编码在代码中的appsecret、token等等，而通常情况下这种秘钥复杂程度很高。
然后也加上了password、passwd这种检测的支持，这里默认一般情况下企业使用的密码为强口令。

所以目前不支持admin_password、admin123这种弱口令检测，也是个两难问题。
