### ISSUE TITLE
Hi,插件有用到Log4j吗

### ISSUE THREAD

**Issue by bansh2eBreak** [momosecurity/momo-code-sec-inspector-java#13]
Hi，大佬，
我在阅读咱们源码的时候看到有如下截图，想请问下咱们momo安全插件有使用Log4j组件吗

![image](https://user-images.githubusercontent.com/23254717/159389771-c0b425a6-0ccf-4719-bd6c-28d63524bd29.png)

期待得到回复

**Comment by retanoj** [comment]
插件本身没有用到Log4j
但是插件跑在IDEA上，IDEA是有引入Log4j 1.x版本组件的
