### ISSUE TITLE
修复后 IDEA仍提示有error

### ISSUE THREAD

**Issue by wjcIvan** [momosecurity/momo-code-sec-inspector-java#3]
IDEA版本:2020.2
原代码
![image](https://github.com/wjcIvan/PictureRepository/blob/main/issue/93e882d532679e7c2807d3fb95e32e6.png?raw=true)
修复后
![image](https://github.com/wjcIvan/PictureRepository/blob/main/issue/0bd23c49eda7349dcc3e7b74dc12c34.png?raw=true)

**Comment by retanoj** [comment]
> IDEA版本:2020.2
> 原代码
> ![image](https://github.com/wjcIvan/PictureRepository/blob/main/issue/93e882d532679e7c2807d3fb95e32e6.png?raw=true)
> 修复后
> ![image](https://github.com/wjcIvan/PictureRepository/blob/main/issue/0bd23c49eda7349dcc3e7b74dc12c34.png?raw=true)

测试版本
IntelliJ IDEA 2020.2 (Community Edition)
Build #IC-202.6397.94, built on July 27, 2020
Runtime version: 11.0.7+10-b944.20 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 512M
Cores: 4
Non-Bundled Plugins: Momo Code Sec Inspector (Java)

该问题未能复现。

**Comment by wjcIvan** [comment]
> > IDEA版本:2020.2
> > 原代码
> > ![image](https://github.com/wjcIvan/PictureRepository/blob/main/issue/93e882d532679e7c2807d3fb95e32e6.png?raw=true)
> > 修复后
> > ![image](https://github.com/wjcIvan/PictureRepository/blob/main/issue/0bd23c49eda7349dcc3e7b74dc12c34.png?raw=true)
> 
> 测试版本
> IntelliJ IDEA 2020.2 (Community Edition)
> Build #IC-202.6397.94, built on July 27, 2020
> Runtime version: 11.0.7+10-b944.20 x86_64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> macOS 10.15.7
> GC: G1 Young Generation, G1 Old Generation
> Memory: 512M
> Cores: 4
> Non-Bundled Plugins: Momo Code Sec Inspector (Java)
> 
> 该问题未能复现。

新版本的问题？ 
IntelliJ IDEA 2020.2.3 (Ultimate Edition)  
Build #IU-202.7660.26, built on October 6, 2020

**Comment by retanoj** [comment]
同样未能复现。
怀疑并不是版本问题，而是IDEA卡顿问题

**Comment by wjcIvan** [comment]
> 同样未能复现。
> 怀疑并不是版本问题，而是IDEA卡顿问题

可疑的缓存问题 当我删除 `and createdBy` 然后重新输入 `and createdBy` 就正常了 我再验证一下是插件还是IDEA的问题

**Comment by retanoj** [comment]
插件过程：
Fix功能 会让 `and createdBy LIKE '%${createdBy}%'` 变成 `and createdBy LIKE CONCAT('%', #{createdBy}, '%')`

随后该XML中的`Text`部分会重新触发Inspector检查，当检查到 `and createdBy LIKE CONCAT('%', #{createdBy}, '%')`的时候，未发现问题，因此就不会再报出ERROR下划线了

**Comment by retanoj** [comment]
感谢关注，先关闭该issue。如有问题，欢迎继续留言。
