### ISSUE TITLE
idea 2019安装插件后，未弹出示例里可以选择自动修复的提示框

### ISSUE THREAD

**Issue by huangwei110** [momosecurity/momo-code-sec-inspector-java#4]
![image](https://user-images.githubusercontent.com/11372733/96087167-06936a00-0ef6-11eb-85b1-5edbf543adc1.png)

**Comment by retanoj** [comment]
能否提供详细版本与发生问题的样例代码？
详细版本：菜单栏 -> Intellij IDEA -> About Intellij IDEA -> 复制内容

**Comment by retanoj** [comment]
谢谢关注。
经查，该规则不支持”一键修复“。

|编号|规则名称|修复建议|一键修复|
|-|-|-|-|
|1018|宽泛的CORS Allowed Origin设置|T||

**Comment by huangwei110** [comment]
好的，谢谢
