### ISSUE TITLE
1020：硬编码凭证风险为啥无法检测？

### ISSUE THREAD

**Issue by nvyao** [momosecurity/momo-code-sec-inspector-java#5]
第一种：
public class ProducerTest {
    public static void main(String[] args) {
        Properties properties = new Properties();
        // AccessKey 阿里云身份验证，在阿里云用户信息管理控制台获取
        properties.put(PropertyKeyConst.AccessKey,"L4534GH11FXqsEtyZfbchwuP");
        // SecretKey 阿里云身份验证，在阿里云用户信息管理控制台获取
        properties.put(PropertyKeyConst.SecretKey, "SHF8WVOF11jSIaY5OnZ3KlAARRePdk");

第二种：
public static final String FORGET_PASSWORD = "password";

上面两类都无法检测，请问有测试代码吗

**Comment by retanoj** [comment]
感谢反馈
第一种场景目前不支持，不过考虑增加该场景的检测。
第二种场景支持，没有提示风险的原因是1020规则目前对”凭证“的定义需要有一定的复杂度。

测试代码在：src/test/java/com/immomo/momosec/lang/java/rule/momosecurity/HardcodedCredentialsTest.java
测试样例在：src/test/testData/lang/java/rule/momosecurity/HardcodedCredentials/Vuln.java

**Comment by retanoj** [comment]
该问题将会在version x.13中解决
