### ISSUE TITLE
[Bug]插件使用问题

### ISSUE THREAD

**Issue by coffeehb** [momosecurity/momo-code-sec-inspector-java#6]
**问题描述**

使用的193.15版本，testcase 里的一些mybatis的写法没有检测出问题

**复现方法**

使用的193.15版本插件和 Vuln.xml文件 测试
https://github.com/momosecurity/momo-code-sec-inspector-java/blob/2018.3/src/test/testData/lang/xml/rule/momosecurity/MybatisXmlSQLi/Vuln.xml

**问题截图**

如果可以，请提供截图以帮助进一步确认问题。
![image](https://user-images.githubusercontent.com/5829776/104423082-952c8b80-55b8-11eb-8fff-e483df38fae8.png)

**软件版本**

IDEA 社区办 2019.2
插件193.15版本

IntelliJ IDEA 2019.2 (Community Edition)
Build #IC-192.5728.98, built on July 23, 2019
Runtime version: 11.0.3+12-b304.10 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: debugger.watches.in.variables=false, git.explicit.commit.renames.prohibit.multiple.calls=false
Non-Bundled Plugins: FindBugs-IDEA, Jar Tool, com.dmitz.intellij.plugin.websocket.client, com.github.gtache.lsp, Momo Code Sec Inspector (Java), me.vukas.remote-debug, mobi.hsz.idea.gitignore, MavenRunHelper, Docker, aws.toolkit, org.sonarlint.idea, ru.basecode.ide.rest.plugin

**Comment by retanoj** [comment]
如图，<when> 块的防止位置是不是不符合mybatis mapper xml的语法？

**Comment by retanoj** [comment]
因为误报等原因，目前在SQL注入漏洞的变量拼接位置上过滤了部分内容。
详见`src/main/java/com/immomo/momosec/utils/SQLi.java`

**Comment by coffeehb** [comment]
好的，明白～
