### ISSUE TITLE
可以为 MyBatis-Plus 的 Wrapper 设置一个白名单吗（sql注入，$符号）

### ISSUE THREAD

**Issue by chenbihao** [momosecurity/momo-code-sec-inspector-java#8]
如题，mp的条件构造器会在sql后面拼接`${ew.customSqlSegment}`，是否可以加进白名单里?

**Comment by retanoj** [comment]
> 如题，mp的条件构造器会在sql后面拼接`${ew.customSqlSegment}`，是否可以加进白名单里?

抱歉这么久才回复。

这个在MyBatis 生成的xml 里是会白名单掉${ew.*} 这种拼入的部分的。
能提供一下具体的案例吗？我来排查下。

**Comment by chenbihao** [comment]
> > 如题，mp的条件构造器会在sql后面拼接`${ew.customSqlSegment}`，是否可以加进白名单里?
> 
> 抱歉这么久才回复。
> 
> 这个在MyBatis 生成的xml 里是会白名单掉${ew.*} 这种拼入的部分的。
> 能提供一下具体的案例吗？我来排查下。

比如这样
```
// 这样会报
@Select("select t.* ,p.name from detection t ${ew.customSqlSegment}")

// 单独不会
@Select("${ew.customSqlSegment}")

// 包含其他内容，如空格都会报
@Select(" ${ew.customSqlSegment}")

```

**Comment by retanoj** [comment]
该问题将于 193.17 版本优化处理
