### ISSUE TITLE
期望有主动扫描代码的功能

### ISSUE THREAD

**Issue by hbbbs** [momosecurity/momo-code-sec-inspector-java#9]
项目中有不少已经开发完成的功能，希望也能用插件扫描一下是否存在安全隐患。

期望有一个主动扫描的功能，对项目中所有文件进行扫描！  

谢谢momo团队提供的这么好用的插件！

**Comment by retanoj** [comment]
感谢关注陌陌安全。 IDEA 其实自身提供主动扫描功能。
![image](https://user-images.githubusercontent.com/6688779/118943606-5bb0c600-b986-11eb-9e4a-55074f539397.png)
![image](https://user-images.githubusercontent.com/6688779/118943654-65d2c480-b986-11eb-87f2-9ebce1c5e69a.png)

在弹框里可以选择对整项目进行扫描，或者单一文件进行扫描
扫描策略也可以配置使用所有的规则，或者说自定义开启部分规则
